name: auto-pr

on:
  push:
    branches:
    - 4.*-devel

jobs:
  pull-request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set branch variables
      run: BASE_REF=$(echo $GITHUB_REF | cut -f3- -d\/);
           major=$(echo $BASE_REF | cut -f1 -d\.);
           minor=$(echo $BASE_REF | cut -f2 -d\. | cut -f1 -d\-);
           DEST_BRANCH=$major.$((minor+1))-devel;
           git branch -a | grep "origin/$DEST_BRANCH" || {
             DEST_BRANCH=$((major+1)).0-devel;
             git branch -a | grep "origin/$DEST_BRANCH" || exit 1;
           };
           echo "BASE_REF=$BASE_REF" >> $GITHUB_ENV;
           echo "DEST_BRANCH=$DEST_BRANCH" >> $GITHUB_ENV;

    - name: Create Pull Request
      id: open-pr
      run: gh pr create -B $BASE_REF -H $DEST_BRANCH --title "Pull $BASE_REF into $DEST_BRANCH" --body "merge"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Auto approve
      uses: hmarr/auto-approve-action@v4
      with:
        pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
